---
- name: "SCORED | 1.1 | Ensure a separate partition for containers has been created"
  command: "grep /var/lib/docker /etc/fstab"
  changed_when: no
  ignore_errors: yes
  when: cis_rule_1_1
  tags:
    - level1_host
    - scored
    - rule_1.1
    - manual_check

- name: "NOTSCORED manually | 1.2 | Ensure the container host has been Hardened"
  command: "/bin/true"
  changed_when: no
  tags:
    - level1_host
    - scored
    - rule_1.2
    - manual_check

- name: "NOTSCORED manually | 1.3 | Ensure Docker is up to date"
  command: "/bin/true"
  changed_when: no
  tags:
    - level1_host
    - scored
    - rule_1.3
    - manual_check

- name: "SCORED manually | 1.4 | Ensure only trusted users are allowed to control Docker daemon"
  command: "/bin/true"
  changed_when: no
  tags:
    - level1_host
    - scored
    - rule_1.4
    - manual_check

- name: "SCORED | 1.5 | Ensure auditing is configured for the docker daemon"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /usr/bin/docker -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.5

- name: "SCORED | 1.6 | Ensure auditing is configured for Docker files and directories - /var/lib/docker"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /var/lib/docker -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.6

- name: "SCORED | 1.7 | Ensure auditing is configured for Docker files and directories - /etc/docker"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /etc/docker -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.7

- name: "SCORED | 1.8 | Ensure auditing is configured for Docker files and directories - docker.service"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.8

- name: "SCORED | 1.9 | Ensure auditing is configured for Docker files and directories - docker.socket"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /usr/lib/systemd/system/docker.socket -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.9

- name: "SCORED | 1.10 | Ensure auditing is configured for Docker files and directories - /etc/default/docker"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /etc/default/docker -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.10

- name: "SCORED | 1.11 | Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /etc/docker/daemon.json -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.11

- name: "SCORED | 1.12 | Ensure auditing is configured for Docker files and directories - /usr/bin/docker-containerd"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /usr/bin/docker-containerd -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.12

- name: "SCORED | 1.13 | Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc"
  lineinfile:
    state: present
    create: yes
    dest: "{{ auditd_config_file[ansible_os_family] }}"
    line: "-w /usr/bin/docker-runc -k docker"
  notify: load audit rules
  tags:
    - level1_host
    - scored
    - rule_1.13
